FROM midaria/php:latest

# Instalar dependencias del sistema
RUN apk add --no-cache \
    autoconf \
    bash \
    dcron \
    g++ \
    make \
    libpq \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    icu-dev \
    postgresql-dev \
    redis \
    linux-headers

# Instalar extensión de Redis
RUN pecl install redis \
    && docker-php-ext-enable redis

# Extensiones necesarias
RUN docker-php-ext-install pdo_pgsql pgsql sockets pcntl posix fileinfo

# COPY PHP config
COPY docker/config /usr/local/etc/

# Crear directorio de trabajo
WORKDIR /var/www

# Copiar archivos del backend (sin node_modules ni dist aún)
COPY . .

# Permisos
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Cron
COPY docker/cronjob /etc/crontabs/root
RUN touch /var/www/storage/logs/cron.log

COPY docker/dev/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
